### PR TITLE
Optimize some allocations 

### PR DESCRIPTION
**Pull request by tdakkota**

### CODE REVIEW

**Comment by ernado** [comment]
Please rebase to main branch

**Comment by tdakkota** [comment]
With only first commit
```
benchmark                      old ns/op     new ns/op     delta
BenchmarkEncryption/128-4      7555          9740          +28.92%
BenchmarkEncryption/1024-4     21359         21148         -0.99%
BenchmarkEncryption/5000-4     84347         80291         -4.81%

benchmark                      old MB/s     new MB/s     speedup
BenchmarkEncryption/128-4      28.59        22.18        0.78x
BenchmarkEncryption/1024-4     52.06        52.58        1.01x
BenchmarkEncryption/5000-4     60.23        63.27        1.05x

benchmark                      old allocs     new allocs     delta
BenchmarkEncryption/128-4      23             22             -4.35%
BenchmarkEncryption/1024-4     24             23             -4.17%
BenchmarkEncryption/5000-4     24             23             -4.17%

benchmark                      old bytes     new bytes     delta
BenchmarkEncryption/128-4      2676          2516          -5.98%
BenchmarkEncryption/1024-4     6499          5346          -17.74%
BenchmarkEncryption/5000-4     23531         18153         -22.85%
```

With both commits
```
benchmark                      old ns/op     new ns/op     delta
BenchmarkEncryption/128-4      7555          8926          +18.15%
BenchmarkEncryption/1024-4     21359         24508         +14.74%
BenchmarkEncryption/5000-4     84347         120391        +42.73%

benchmark                      old MB/s     new MB/s     speedup
BenchmarkEncryption/128-4      28.59        24.20        0.85x
BenchmarkEncryption/1024-4     52.06        45.37        0.87x
BenchmarkEncryption/5000-4     60.23        42.20        0.70x

benchmark                      old allocs     new allocs     delta
BenchmarkEncryption/128-4      23             21             -8.70%
BenchmarkEncryption/1024-4     24             22             -8.33%
BenchmarkEncryption/5000-4     24             22             -8.33%

benchmark                      old bytes     new bytes     delta
BenchmarkEncryption/128-4      2676          2516          -5.98%
BenchmarkEncryption/1024-4     6499          5346          -17.74%
BenchmarkEncryption/5000-4     23531         17643         -25.02%
```

**Comment by ernado** [comment]
So it got slower after optimization or what? 🤔

**Comment by tdakkota** [comment]
Second commit reduces two allocations to one buffer, but seems like that is inefficiently.
I considered one big allocation is better than two smaller allocations.

**Comment by tdakkota** [comment]
Closing due to #21 contains refactor of `crypto` package.

**Pull request closed without merging**
